// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vtyxfpioyxlkulsedajr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eXhmcGlveXhsa3Vsc2VkYWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzUzMDMsImV4cCI6MjA2MzcxMTMwM30.KE3Phy1Ek9NJb8BeglQL7EVsLc13dWpNkOTj9Nri1dA";

const HERMAS_ADMIN_SUPABASE_URL = "https://udtovezlmxwlarmcqgkc.supabase.co";
const HERMAS_ADMIN_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdG92ZXpsbXh3bGFybWNxZ2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjI0ODMsImV4cCI6MjA2NDg5ODQ4M30.PXnfFli23BlRUnNk2ml9p83dulpvAze0QGqMh_AgUb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: { params: { eventsPerSecond: 10 } },
  }
);
export const hermasAdminSupabase = createClient<Database>(
  HERMAS_ADMIN_SUPABASE_URL,
  HERMAS_ADMIN_SUPABASE_PUBLISHABLE_KEY,
);
