// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtyxfpioyxlkulsedajr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eXhmcGlveXhsa3Vsc2VkYWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzUzMDMsImV4cCI6MjA2MzcxMTMwM30.KE3Phy1Ek9NJb8BeglQL7EVsLc13dWpNkOTj9Nri1dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);